### ISSUE TITLE
需要在RECORD_PATH和INVERTED_INDEX_PATH中路具体要怎么写？

### ISSUE THREAD

**Issue by fsqhn** [RongRongJi/nonebot_plugin_quote#1]
需要在RECORD_PATH和INVERTED_INDEX_PATH中手动创建两个json文件  这段不止到出了啥岔子了，换了好几个写法都提示路径填写错误或找不到文件。想问问标准写法是什么？

另外，QUOTE_SUPERUSER里必须分群设置管理员qq号么？有没有全局的设置的？

**Comment by fsqhn** [comment]
目前写法：RECORD_PATH=\quote\inverted_index.json
INVERTED_INDEX_PATH=\quote\QUOTE_SUPERUSER.json
试过换绝对路径和两边加" ' ' "都不行。就不知道为啥了。

**Comment by fsqhn** [comment]
行吧，改成了RECORD_PATH=D:\nonebot\basin\quote\inverted_index.json
INVERTED_INDEX_PATH=D:\nonebot\basin\quote\QUOTE_SUPERUSER.json

就行了。

不过issue都开了，还是问下。QUOTE_SUPERUSER里必须分群设置管理员qq号么？有没有全局的设置的？

**Comment by RongRongJi** [comment]
首先非常感谢使用！
路径是要写成绝对路径，示例中的写法是在linux操作系统中的示例，所以可能造成了一些不便。
目前是必须分群设置管理员qq号，需要全局管理员的话我可以加一下。

**Comment by RongRongJi** [comment]
已支持全局管理员，可以更新到最新版本。
全局管理员配置GLOBAL_SUPERUSER

**Comment by fsqhn** [comment]
好的，十分感谢。另外，在orc识别后的词语分段上能否手动指定词组？
比如这张图，我看了下，它给识别成了触手"、  "战神"、    "宇宙"、"是"、    "酱丧"、    "无敌"、    "T"、    "女仆"
![QQ图片20230321144918](https://user-images.githubusercontent.com/13745793/226535726-12682c59-e5e7-40c5-a4ca-30834822f137.jpg)
然而事实上，丧T是一位群友的名字，而且把这个酱丧切一起去了也不太对劲。
虽然理论上也能手动改？但好像重启机器人的时候会自动重新识别分段，手改过一次后它自己又变回来了。

**Comment by fsqhn** [comment]
好的，非常感谢。
