### ISSUE TITLE
请教个问题，文件存在哪的呢，是存在互联网上的吗？到期时间是多少呢？

### ISSUE THREAD

**Issue by anlen123** [RongRongJi/nonebot_plugin_quote#2]
请教个问题，文件存在哪的呢，是存在互联网上的吗？到期时间是多少呢？

**Comment by RongRongJi** [comment]
你是指什么文件

**Comment by anlen123** [comment]
图片文件，我到处找都没找到。我想自己导入一些图片，我也做了一个类似的功能，但是不想用我的插件了，想用你这个。

**Comment by RongRongJi** [comment]
图片会自动存在go-cqhttp目录下的data\cache中，是永久保存的。

**Comment by anlen123** [comment]
好家伙，存在那个下面感觉路径不是很合理。应该在data下面比较合理，而不应该在accounts这个下面。我的建议，谢谢解答。

**Comment by anlen123** [comment]
再请教一个问题，图片保存到data/qquid/cache这个路径，代码体现在哪，我实在是没找到，很奇怪啊。

**Comment by RongRongJi** [comment]
保存路径应该是gocqhttp目录下的data/cache，如果不是可能是gocq版本不一致。调用gocq的api会自动下载到该目录
