### ISSUE TITLE
两个建议

### ISSUE THREAD

**Issue by F1Justin** [RongRongJi/nonebot_plugin_quote#4]
1. 建议添加图片库文件夹，以便大批量迁移原有的语录；
2. 建议添加指定某个发送者的语录的功能（图片库可以以发送者为分类来设置文件夹）

**Comment by RongRongJi** [comment]
1. 图片库统一存放在go-cqhttp/data/cache目录下，可以迁移；
2. 语录图片不一定只包含一个人，对于OCR来说，无法区分里面的文字哪个是发言哪个是发送者的名字：
  为了更方便使用语录，在v0.3.0版本中增加了标签功能，可以辅助用户更好地进行筛选，具体功能如下：

### 增加/删除标签

回复语录图片，发送**addtag**+标签（addtag后需加空格，可以多个标签，每个标签之间用空格分隔），为指定语录增加额外标签。

回复语录图片，发送**deltag**+标签（deltag后需加空格，可以多个标签，每个标签之间用空格分隔），为指定语录删除不需要的标签。

<img src="https://github.com/RongRongJi/nonebot_plugin_quote/raw/main/screenshot/tag.jpg" width="40%" />

### 指定标签检索语录

@机器人，发送**语录**+#号+标签，将从语录库中对指定标签进行查找。加#号后，将只对#号后的完整的词进行查找；不加#号会进行分词。

<img src="https://github.com/RongRongJi/nonebot_plugin_quote/raw/main/screenshot/usetag.jpg" width="40%" />

### 详细命令

默认配置下，@机器人加指令即可。

| 指令 | 需要@ | 范围 | 说明 |
|:-----:|:----:|:------:|:-----------:|
| 语录 + #标签 | 是 | 群聊 | 根据标签返回一个符合要求的图片, 没有关键词时随机返回 |
| 回复机器人 + addtag + 标签(addtag和标签之间需要空格)| 是 | 群聊 | 为该条语录增加额外标签 |
| 回复机器人 + deltag + 标签(deltag和标签之间需要空格)| 是 | 群聊 | 为该条语录删除指定标签 |
| 回复机器人 + alltag| 是 | 群聊 | 查看该条语录所有标签 |

**Comment by F1Justin** [comment]
谢谢，是否可以再新增决定是否需要@机器人的配置？每次都要@感觉有些不便

**Comment by RongRongJi** [comment]
好的，我增加一下。
问一句题外话，请问你是否有出现[issue#5](https://github.com/RongRongJi/nonebot_plugin_quote/issues/5#issue-1642959548)这种，无法删除的情况？

**Comment by F1Justin** [comment]
> 好的，我增加一下。
> 问一句题外话，请问你是否有出现[issue#5](https://github.com/RongRongJi/nonebot_plugin_quote/issues/5#issue-1642959548)这种，无法删除的情况？
我这边是正常的

**Comment by RongRongJi** [comment]
> > 好的，我增加一下。
> > 问一句题外话，请问你是否有出现[issue#5](https://github.com/RongRongJi/nonebot_plugin_quote/issues/5#issue-1642959548)这种，无法删除的情况？
> > 我这边是正常的

感谢反馈

**Comment by F1Justin** [comment]
之前一直使用nonebot-plugin-random实现随机抽语录的功能，大约积累了500+条图片形式的语录。如果能够帮忙迁移的话，是在感激不尽！
（另外，迁移工具可否有批量添加标签的功能？

**Comment by RongRongJi** [comment]
好的，会尽量考虑

**Comment by RongRongJi** [comment]
> 谢谢，是否可以再新增决定是否需要@机器人的配置？每次都要@感觉有些不便

v0.3.2中已实现

**Comment by RongRongJi** [comment]
> 之前一直使用nonebot-plugin-random实现随机抽语录的功能，大约积累了500+条图片形式的语录。如果能够帮忙迁移的话，是在感激不尽！ （另外，迁移工具可否有批量添加标签的功能？

目前的OCR功能是直接调用qq内置的OCR实现的，要使用qq内置OCR就必须让该图片通过聊天发送一次。如果需要实现大规模迁移，我有三种方案：
1. 直接跳过OCR，一次性将大批量图片划分到指定群的语录库中，并为他们统一输入一个或多个标签；
2. 为大批量图片设置群号和统一标签后，机器人通过私聊窗口逐一发送图片，逐一进行OCR；
3. 开放一个函数，基于方法1的基础上，支持调用自己的OCR方法，但插件本身不会提供。

方法1速度快，缺点就是同一批图片只拥有一个或多个相同的标签；
方法2就是模拟上传，功能上完全符合，就是机器人账号会发送较多图片，会增加时延来防风控，耗时长；
方法3需要自己实现OCR方法（我可以提供一个例子，但不会集成进插件）

您觉得哪一种更合适？

**Comment by RongRongJi** [comment]
> > 提供
> 
> 我认为第二种方法较为合适，因为迁移的过程对时效不敏感。另外想问一下，统一输入标签是第一种方法独有的吗？

三种都可以支持

**Comment by RongRongJi** [comment]
已实现，请更新至[v0.3.3](https://github.com/RongRongJi/nonebot_plugin_quote/releases/tag/v0.3.3)

**Comment by F1Justin** [comment]
上传时遇到错误，下面是群聊截图和nb控制台记录的消息

<img width="715" alt="截屏2023-04-02 18 19 14" src="https://user-images.githubusercontent.com/30348215/229347055-721440a4-601e-4642-ba2e-fddc0460080f.png">

04-02 18:13:07 [SUCCESS] nonebot | OneBot V11 985393579 | [message.group.normal]: Message -16349834 from 2843657817@[群:708309706] 'batch_upload\nqqgroup=708309706\nyour_path=/Users/justin/QQbot/uuz/data/random/飞舞语录\ngocq_path=/Users/justin/QQbot/go-cqhttp_darwin_amd64/data/cache\ntags=飞舞 可爱 小飞舞'
04-02 18:13:07 [DEBUG] nonebot | Running PreProcessors...
04-02 18:13:07 [DEBUG] nonebot | Checking for matchers in priority 0...
04-02 18:13:07 [DEBUG] nonebot | Checking for matchers in priority 1...
04-02 18:13:07 [INFO] nonebot | Event will be handled by Matcher(type='message', module=nonebot_plugin_quote)
04-02 18:13:07 [DEBUG] nonebot | Running Matcher(type='message', module=nonebot_plugin_quote)
04-02 18:13:07 [DEBUG] nonebot | Running handler Dependent(call=script_batch_handle)
04-02 18:13:08 [DEBUG] nonebot | OneBot V11 | Calling API send_msg
04-02 18:13:09 [DEBUG] nonebot | Running CalledAPI hooks...
04-02 18:13:09 [ERROR] nonebot | Error when running CalledAPI hook. Running cancelled!
Traceback (most recent call last):
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot_plugin_quote/__init__.py", line 520, in script_batch_handle
    msg_id = await bot.send_msg(group_id=int(groupNum), message='[CQ:image,file={}]'.format(save_file))
> File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/internal/adapter/bot.py", line 107, in call_api
    await asyncio.gather(*coros)
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot_plugin_chatrecorder/__init__.py", line 96, in record_send_msg_v11
    or (api == "send_msg" and data["message_type"] == "group")
KeyError: 'message_type'
04-02 18:13:11 [INFO] nonebot | Matcher(type='message', module=nonebot_plugin_quote) running complete
04-02 18:13:11 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_quote) failed.
Traceback (most recent call last):
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/internal/matcher/matcher.py", line 707, in simple_run
    await handler(
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot/dependencies/__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "/Users/justin/opt/miniconda3/envs/bot/lib/python3.10/site-packages/nonebot_plugin_quote/__init__.py", line 522, in script_batch_handle
    if save_file in forward_index[group_id[0]]:
KeyError: '708309706'
04-02 18:13:11 [DEBUG] nonebot | Stop event propagation
04-02 18:13:11 [DEBUG] nonebot | Checking for matchers completed
04-02 18:13:11 [DEBUG] nonebot | Running PostProcessors...

**Comment by RongRongJi** [comment]
感谢测试并发现问题，已更新v0.3.4修复

**Comment by F1Justin** [comment]
可以了，谢谢！
