### ISSUE TITLE
删除指令似乎无法触发

### ISSUE THREAD

**Issue by Sevenyine** [RongRongJi/nonebot_plugin_quote#5]
.env 配置文件：
`COMMAND_START=[“.”]`
后台无ERROR报错，均是nonebot_plugin_quote running complete
截图：
![9CE9458D-A34D-49C9-B04F-A5998C9A89B2](https://user-images.githubusercontent.com/65720409/228087433-71edc4d7-a7bf-4dee-8a3f-cd154de9a4a4.jpeg)

**Comment by RongRongJi** [comment]
如果还是不行，检查版本是否在此及以上。


nonebot2 = "^2.0.0rc3"
nonebot-adapter-onebot = "^2.2.1"

go-cqhttp = "^1.0.0-rc3"

出现“请回复需要删除的语录, 并输入删除指令”提示有两种可能：
1. 该条消息内容无法被读取为``` [reply:id=xxxx][at:qq=xxxx] [at:qq=xxxx] .删除``` ，可以在控制台看看消息是否正确
2. 被回复的内容（即reply:id所指的那条记录）无法被读取为 ```[image:file=xxxx, subType=xxx, url=xxxx] ```

**Comment by Sevenyine** [comment]
> 如果还是不行，检查版本是否在此及以上。
> 
> nonebot2 = "^2.0.0rc3" nonebot-adapter-onebot = "^2.2.1"
> 
> go-cqhttp = "^1.0.0-rc3"
> 
> 出现“请回复需要删除的语录, 并输入删除指令”提示有两种可能：
> 
> 1. 该条消息内容无法被读取为` [reply:id=xxxx][at:qq=xxxx] [at:qq=xxxx] .删除` ，可以在控制台看看消息是否正确
> 2. 被回复的内容（即reply:id所指的那条记录）无法被读取为 `[image:file=xxxx, subType=xxx, url=xxxx] `

我这里上传了两条还是不行，版本确认无误。

第一条确认是可以被读取为以上格式的。
第二条，如何查询reply id对应记录的消息呢？后台不会打印自己发出消息的那条记录。还需要别的账号查看吗
ps：经过测试，加tag也不可以正常触发，怀疑是第二条的问题

**Comment by RongRongJi** [comment]
回复你自己发的图片并且at机器人也可以触发，这样可以看到记录。

**Comment by Sevenyine** [comment]
在gocqhttp里开启为reply增加更多消息的配置后，服务器出现报错如下。
然而每次我都是bot重启后重新让他发送的语录，不清楚为什么会出现这样的报错

```
03-28 13:11:07 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_quote) failed.
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\NoneBot\GZbot2\bot.py", line 36, in <module>
    nonebot.run(app="__mp_main__:app")
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
    get_driver().run(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
    uvicorn.run(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
    server.run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
    return asyncio.run(self.serve(sockets=sockets))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
    self._run_once()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
    handle._run()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
    await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
    await matcher.run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
    await self.simple_run(bot, event, state, stack, dependency_cache)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
    await handler(
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
    return await cast(Callable[..., Awaitable[R]], self.call)(**values)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_quote\__init__.py", line 233, in delete_record_handle
    resp = await bot.get_msg(message_id=ids[0])
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
    raise exception
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
    result = await self.adapter._call_api(self, api, **data)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 140, in _call_api
    return handle_api_result(await self._result_store.fetch(seq, timeout))
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
    raise ActionFailed(**result)
nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='19', msg='MSG_NOT_FOUND', retcode=100, status='failed', wording='消息不存在')
```

**Comment by Sevenyine** [comment]
> 回复你自己发的图片并且at机器人也可以触发，这样可以看到记录。

感谢提醒！我发现机器人收到的确实不是这个格式，而是如下图
qq内截图：
![94CA99BC-4C41-45AD-B2FD-F87F6E629513](https://user-images.githubusercontent.com/65720409/228135040-d20620d9-f1fb-4227-b84b-d1642ca64fe4.jpeg)

![992AD447-C4B6-4DCF-A72D-ED487F9FC97D](https://user-images.githubusercontent.com/65720409/228134948-8dfe16a3-3f9e-435b-8ae0-33ec1791385b.jpeg)

**Comment by RongRongJi** [comment]
>![BFC0FF41-FA40-4E64-9E7F-00FC3B4E7A91](https://user-images.githubusercontent.com/65720409/228135298-f51e341e-601b-4e96-9332-8d6cead22ba7.jpeg)

这就是原因了，我这里的回复消息的格式是``` [reply:id=xxxx][at:qq=xxxx] [at:qq=xxxx]```，而你收到的是```[reply:id=xxx, seq=xxx, qq=xxx, time=xxx, text=xxx][at:qq=xxx] [at:qq=xxx]```。
我根据正则匹配[reply:id=(.*?)]来获取图片消息的内容，因此这里出现了错误。

**Comment by Sevenyine** [comment]
> > ![BFC0FF41-FA40-4E64-9E7F-00FC3B4E7A91](https://user-images.githubusercontent.com/65720409/228135298-f51e341e-601b-4e96-9332-8d6cead22ba7.jpeg)
> 
> 这就是原因了，我这里的回复消息的格式是` [reply:id=xxxx][at:qq=xxxx] [at:qq=xxxx]`，而你收到的是`[reply:id=xxx, seq=xxx, qq=xxx, time=xxx, text=xxx][at:qq=xxx] [at:qq=xxx]`。 我根据正则匹配[reply:id=(.*?)]来获取图片消息的内容，因此这里出现了错误。

请问一下您的qq客户端和版本是什么（？）我可能是因为更新了qq 他的reply也变了

**Comment by RongRongJi** [comment]
windows的qq版本是9.7.3，安卓端的是8.9.35

**Comment by RongRongJi** [comment]
已更新v0.3.1版本对这个问题做了适配，你试一下

**Comment by Sevenyine** [comment]
> 已更新v0.3.1版本对这个问题做了适配，你试一下

感谢！不过我发现好像并不是这个问题，我通过更新到0.3.1，打开gocq配置，仍然出现错误。
![311D2385-434A-41ED-AECA-1E050835A56E](https://user-images.githubusercontent.com/65720409/228141673-37c92f66-a676-4df5-8113-8e9512c68043.jpeg)

这个格式差是我打开了gocq里面的reply加更多信息导致的，如果关掉了就恢复正常了（和您给的格式一样）
![11784554-12D3-428F-A928-654172C21F33](https://user-images.githubusercontent.com/65720409/228141688-80474bab-3d78-4b6d-aa0e-6448a9127057.jpeg)

我本来怀疑是reply id的问题，但是检查了一下发现是对的上的。
![E359B487-5A05-47DA-B4FD-17168EA4350E](https://user-images.githubusercontent.com/65720409/228142253-9360a7df-6808-4fd9-af9f-079eaae8f210.jpeg)

人傻了🫠

**Comment by RongRongJi** [comment]
> 在gocqhttp里开启为reply增加更多消息的配置后，服务器出现报错如下。 然而每次我都是bot重启后重新让他发送的语录，不清楚为什么会出现这样的报错
> 
> ```
> 03-28 13:11:07 [ERROR] nonebot | Running Matcher(type='message', module=nonebot_plugin_quote) failed.
> Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\NoneBot\GZbot2\bot.py", line 36, in <module>
>     nonebot.run(app="__mp_main__:app")
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\__init__.py", line 273, in run
>     get_driver().run(*args, **kwargs)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\drivers\fastapi.py", line 187, in run
>     uvicorn.run(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\main.py", line 569, in run
>     server.run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\uvicorn\server.py", line 60, in run
>     return asyncio.run(self.serve(sockets=sockets))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\runners.py", line 44, in run
>     return loop.run_until_complete(main)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 636, in run_until_complete
>     self.run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\windows_events.py", line 321, in run_forever
>     super().run_forever()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 603, in run_forever
>     self._run_once()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\base_events.py", line 1906, in _run_once
>     handle._run()
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\asyncio\events.py", line 80, in _run
>     self._context.run(self._callback, *self._args)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 141, in _check_matcher
>     await _run_matcher(Matcher, bot, event, state, stack, dependency_cache)
> > File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\message.py", line 187, in _run_matcher
>     await matcher.run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 732, in run
>     await self.simple_run(bot, event, state, stack, dependency_cache)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\matcher\matcher.py", line 707, in simple_run
>     await handler(
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\dependencies\__init__.py", line 108, in __call__
>     return await cast(Callable[..., Awaitable[R]], self.call)(**values)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot_plugin_quote\__init__.py", line 233, in delete_record_handle
>     resp = await bot.get_msg(message_id=ids[0])
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 120, in call_api
>     raise exception
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\internal\adapter\bot.py", line 98, in call_api
>     result = await self.adapter._call_api(self, api, **data)
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\adapter.py", line 140, in _call_api
>     return handle_api_result(await self._result_store.fetch(seq, timeout))
>   File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\site-packages\nonebot\adapters\onebot\v11\utils.py", line 58, in handle_api_result
>     raise ActionFailed(**result)
> nonebot.adapters.onebot.v11.exception.ActionFailed: ActionFailed(data=None, echo='19', msg='MSG_NOT_FOUND', retcode=100, status='failed', wording='消息不存在')
> ```

看看v0.3.1版本是否还会出现这个错误？
如果没有出现这个错误，那就是reply已经被正确找到。

之后，将调用以下方法获取该条回复的信息。
```
resp = await bot.get_msg(message_id=reply_id)
img_msg = str(resp['message'])
print(img_msg)
```
在这里我所打印出来的信息格式是```[CQ:image,file=xxxf.image,subType=xxx,url=xxxx]```，后续的解析建立在这个格式之上。不知道你能否在这里测试一下这个输出结果，可以在nonebot-plugin-quote包中__init__.py的第436行添加一个print(img_msg)来看看这个结果。

**Comment by Sevenyine** [comment]
确实是这里出现的问题，我这里提取到的格式不一样🤔
![1FE7907A-491A-4647-9328-C019DE1C313C](https://user-images.githubusercontent.com/65720409/228180436-ccf9f129-e20d-4ad4-b983-1644c1f7690e.jpeg)

**Comment by RongRongJi** [comment]
我把cqhttp更新到最新的1.0.0rc5仍然没有复现。我对bot.get_msg(message_id=reply_id)的返回结果是
![image](https://user-images.githubusercontent.com/32476024/228214334-a93074aa-92c4-4360-a6cf-d21a7f4006b2.png)

你看看是否能将cqhttp更新到最新版本试一试？
还有一种可能就是我的nonebot这边版本比你低，他无法向下兼容，方便提供一下你的版本吗

**Comment by Sevenyine** [comment]
> 我把cqhttp更新到最新的1.0.0rc5仍然没有复现。我对bot.get_msg(message_id=reply_id)的返回结果是 ![image](https://user-images.githubusercontent.com/32476024/228214334-a93074aa-92c4-4360-a6cf-d21a7f4006b2.png)
> 
> 你看看是否能将cqhttp更新到最新版本试一试？ 还有一种可能就是我的nonebot这边版本比你低，他无法向下兼容，方便提供一下你的版本吗

gocq我的是rc4，更新至rc5仍然有这样的问题。nb是2.0.0rc3 nb_cli 1.0.0

**Comment by RongRongJi** [comment]
本质就是bot.get_msg的返回结果不一样。排除了nb和gocq的版本问题，或许是其他插件重载了这个方法？

**Comment by Sevenyine** [comment]
> 本质就是bot.get_msg的返回结果不一样。排除了nb和gocq的版本问题，或许是其他插件重载了这个方法？

我重新开了个bot，用go rc5 和 nb rc3 只装了这一个插件，还是不行😭
![C806A610-EEB0-455A-98D2-9976C7C7B46D](https://user-images.githubusercontent.com/65720409/228230886-bd407479-3d3d-4a26-af29-5941ca990906.jpeg)
不过我在翻阅机器人其他能用的回复插件时，翻到一个回复搜图的插件，在bot上是可以用的，而没有出现get_msg，可能是get_msg的问题？不知道能不能通过更换调用方式解决
https://github.com/noneplugin/nonebot-plugin-hikarisearch/blob/main/nonebot_plugin_hikarisearch/__init__.py

**Comment by Sevenyine** [comment]
我又通过print打印了变量，其中，rt和ids无误，
resp: {'group': True, 'group_id': 814037586, 'message': [{'type': 'image', 'data': {'file': '13f8b7eef5fc3e431570798feb3cbc37.image', 'subType': '0', 'url': 'https://gchat.qpic.cn/gchatpic_new/1/0-0-13F8B7EEF5FC3E431570798FEB3CBC37/0?term=2'}}], 'message_id': 1581866169, 'message_id_v2': '0000000030853a520000557f', 'message_seq': 21887, 'message_type': 'group', 'real_id': 21887, 'sender': {'nickname': '必须咕了', 'user_id': qq号}, 'time': 1680006918}
img_msg：[{'type': 'image', 'data': {'file': '13f8b7eef5fc3e431570798feb3cbc37.image', 'subType': '0', 'url': 'https://gchat.qpic.cn/gchatpic_new/1/0-0-13F8B7EEF5FC3E431570798FEB3CBC37/0?term=2'}}]
能否让程序尝试从这个img_msg中提取file变量呢

**Comment by Sevenyine** [comment]
我通过修改rt=的正则表达式，终于解决了这个问题（😭）
![6071307A-EF0B-411E-9D07-4552177EA954](https://user-images.githubusercontent.com/65720409/228257192-98630e6d-00b8-4575-83de-2060ff84bb7a.jpeg)
修改后如下：
`rt = r"\[{'type': 'image', 'data': {'file': '(.*?)', 'subType': '[\S]*', 'url': '[\S]*'}}]"`
那这个问题应该算解决了（？）虽然原因没找到但是能修复了，感谢大佬的帮助！！

**Comment by RongRongJi** [comment]
嗯，但是这样不是一个通用性的解决方法，只能临时解决一下你这里的情况😂

> 不过我在翻阅机器人其他能用的回复插件时，翻到一个回复搜图的插件，在bot上是可以用的，而没有出现get_msg，可能是get_msg的问题？不知道能不能通过更换调用方式解决
https://github.com/noneplugin/nonebot-plugin-hikarisearch/blob/main/nonebot_plugin_hikarisearch/__init__.py

后续更新的时候我参考一下这个吧

**Comment by RongRongJi** [comment]
你的协议是Android Watch吗

**Comment by Sevenyine** [comment]
> 嗯，但是这样不是一个通用性的解决方法，只能临时解决一下你这里的情况😂
> 
> > 不过我在翻阅机器人其他能用的回复插件时，翻到一个回复搜图的插件，在bot上是可以用的，而没有出现get_msg，可能是get_msg的问题？不知道能不能通过更换调用方式解决
> > https://github.com/noneplugin/nonebot-plugin-hikarisearch/blob/main/nonebot_plugin_hikarisearch/__init__.py
> 
> 后续更新的时候我参考一下这个吧

大佬不急！可以用修改正则暂时替代一下🥳
毕竟这个就是改几行代码的事（）

**Comment by Sevenyine** [comment]
（刚没看见第一行）好滴！那我先这么用着，感谢啦🥳
我的协议是android pad

**Comment by RongRongJi** [comment]
怀疑协议不同可能get_msg结果会不同，我是Android Watch，不过我暂时无法复现。我账号只能使用Watch协议来登录😂

**Comment by yhzcake** [comment]
我在使用addtag的时候也出现了这个问题，不过回复的是请回复需要指定语录
我的回复格式是[reply:id=(.*?)]

**Comment by RongRongJi** [comment]
> 我在使用addtag的时候也出现了这个问题，不过回复的是请回复需要指定语录 我的回复格式是[reply:id=(.*?)]

你的cqhttp协议是Android Watch吗？
怀疑协议不同可能会造成正则不匹配的情况，可以根据上面的讨论修改正则。

**Comment by yhzcake** [comment]
是apad，行，我自己修修正则

**Comment by PPPPParas** [comment]
我也遇到了同样的问题，并且addtag也发生类似的错误。回复格式
![bug](https://user-images.githubusercontent.com/91717560/231450676-c203589d-5654-4b79-9c75-4b47b2bfa57a.png)
版本rc5，协议也是Android Watch

**Comment by RongRongJi** [comment]
> 我也遇到了同样的问题，并且addtag也发生类似的错误。回复格式 ![bug](https://user-images.githubusercontent.com/91717560/231450676-c203589d-5654-4b79-9c75-4b47b2bfa57a.png) 版本rc5，协议也是Android Watch

你开启了reply附加信息，所以出现了不匹配。在go-cqhttp的config.yml中关闭即可。
```
  # 为Reply附加更多信息
  extra-reply-data: false
```

**Comment by PPPPParas** [comment]
> > 我也遇到了同样的问题，并且addtag也发生类似的错误。 回复格式 ![错误](https://user-images.githubusercontent.com/91717560/231450676-c203589d-5654-4b79-9c75-4b47b2bfa57a.png) 版本rc5，协议也是Android Watch
> 
> 你开启了reply附加信息，所以出现了不匹配。 在go-cqhttp的config.yml中关闭即可。
> 
> ```
>   # 为Reply附加更多信息
>   extra-reply-data: false
> ```

感谢回复
在关闭了附加信息后依然出现了这个问题
![bug2](https://user-images.githubusercontent.com/91717560/231467120-0b530a19-1d65-4b57-9562-41f251ed8027.png)

![截图](https://user-images.githubusercontent.com/91717560/231467377-393423d3-10fe-428a-9c1c-b22315d1e611.png)

**Comment by Sevenyine** [comment]
> > > 我也遇到了同样的问题，并且addtag也发生类似的错误。 回复格式 ![错误](https://user-images.githubusercontent.com/91717560/231450676-c203589d-5654-4b79-9c75-4b47b2bfa57a.png) 版本rc5，协议也是Android Watch
> > 
> > 
> > 你开启了reply附加信息，所以出现了不匹配。 在go-cqhttp的config.yml中关闭即可。
> > ```
> >   # 为Reply附加更多信息
> >   extra-reply-data: false
> > ```
> 
> 感谢回复 在关闭了附加信息后依然出现了这个问题 ![bug2](https://user-images.githubusercontent.com/91717560/231467120-0b530a19-1d65-4b57-9562-41f251ed8027.png)
> 
> ![截图](https://user-images.githubusercontent.com/91717560/231467377-393423d3-10fe-428a-9c1c-b22315d1e611.png)

https://github.com/RongRongJi/nonebot_plugin_quote/issues/5#issuecomment-1486915366
按照最下面的正则进行修改就可以

**Comment by RongRongJi** [comment]
这个问题确实是一个普遍问题，由于我的账号只能用Watch协议登录，无法对其他协议进行适配，在这个问题上不太好做更新。
我刚刚创建了一个交流群580407499，如果可以，欢迎大家进来交流，对我在这一个功能点上做更新很有帮助。
