### ISSUE TITLE
【功能建议】指令前缀

### ISSUE THREAD

**Issue by Sevenyine** [RongRongJi/nonebot_plugin_quote#6]
可以给quote插件单独加个前缀嘛(*≧ω≦)通过.env 配置，默认空
原因：部分指令（addtag）与部分插件（ELF_RSS）的指令冲突了 也是为了防止误触发。
感谢！

**Comment by RongRongJi** [comment]
v0.3.2中已实现

不过你更新完又要重新修改一次正则😷
