### ISSUE TITLE
【功能建议】上传取消指令

### ISSUE THREAD

**Issue by Sevenyine** [RongRongJi/nonebot_plugin_quote#7]
如果在触发了上传指令后想要退出上传进程，似乎没有指令可以做到（？）而且bot会每条消息都回复让他上传图片形式…>_<…
希望能加一个取消上传的指令，可以取消上传，感谢！

**Comment by RongRongJi** [comment]
直接发送  结束 或者 结束上传 就可以终止

**Comment by Sevenyine** [comment]
> 直接发送 结束 或者 结束上传 就可以终止

好的！不过建议在文档里写一下（）谢谢！
