### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by NovNoah** [RongRongJi/nonebot_plugin_quote#8]
**能否在上传语录时就为其添加标签**
目前添加tag似乎需要Bot将语录发出，可如果语录存储较多，为特点语录添加tag是不是较为困难

**Comment by RongRongJi** [comment]
你可以直接回复你上传的那张图片，@Bot并添加标签

**Comment by NovNoah** [comment]
还能这样，了解了，感谢🙏
