### ISSUE TITLE
一个建议

### ISSUE THREAD

**Issue by mintianzan** [RongRongJi/nonebot_plugin_quote#9]
参考copy_images_files函数，应该可以在保存图片的时候直接保存到用户设定好的image_path，例如bot/resources/image/,这样应该会更便于用户管理资源以及对接其他插件功能

**Comment by RongRongJi** [comment]
保存图片使用cqhttp默认接口自动保存到缓存路径，这样在回复图片时才能正确对应，同时也保证了性能。
管理资源可以定时进行备份: https://github.com/RongRongJi/nonebot_plugin_quote/blob/main/batch.md#-%E6%89%B9%E9%87%8F%E5%A4%87%E4%BB%BD
